### ISSUE TITLE
oppo手機無法使用

### ISSUE THREAD

**Issue by Niekevin007** [longtaoge/SilentCamera#1]
連拍會異常

**Comment by Niekevin007** [comment]
会报takePicture failed 错误、怎么解决呢，作者大大

**Comment by Niekevin007** [comment]
Process: org.xiangbalao.silentCamera, PID: 29273
    java.lang.RuntimeException: takePicture failed
        at android.hardware.Camera.native_takePicture(Native Method)
        at android.hardware.Camera.takePicture(Camera.java:1548)
        at android.hardware.Camera.takePicture(Camera.java:1486)
        at org.xiangbalao.camera.SilentAutoFocusCallback.savePoto(SilentAutoFocusCallback.java:35)
        at org.xiangbalao.camera.SilentAutoFocusCallback.processPoto(SilentAutoFocusCallback.java:27)
        at org.xiangbalao.camera.SilentAutoFocusCallback.onAutoFocus(SilentAutoFocusCallback.java:22)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1217)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:179)
        at android.app.ActivityThread.main(ActivityThread.java:5769)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
